### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pompitzz** [TASK-FORCE/mannalga-front-app#252]
- [ ] 디자인 검수
- [x] 게시판, 사진첩 수정 
- [x] 라우터 일관성 유지
- [x] 만남 취소 모달 텍스트 수정
- [x] webp 적용
- [ ] 운영 환경 테스트 케이스 작성 후 테스트
